spring.application.name=notification_service


#DB CONFIGURATION
#create | create-drop | update | validate | none
spring.datasource.url=jdbc:postgresql://localhost:5432/act-ns
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.sq.notification_service.notification.events
spring.kafka.consumer.properties.spring.json.type.mapping=outbidEvent:com.sq.notification_service.notification.events.bid.outbid.OutbidKafkaEvent
